import type { BuiltInElement } from "@/lib/builtins/types";

const SOURCE = "System Reference Document 5.1";

const SOURCE_URLS = {
  dwarf:
    "https://raw.githubusercontent.com/aurorabuilder/elements/master/core/players-handbook/races/race-dwarf.xml",
  elf: "https://raw.githubusercontent.com/aurorabuilder/elements/master/core/players-handbook/races/race-elf.xml",
  halfling:
    "https://raw.githubusercontent.com/aurorabuilder/elements/master/core/players-handbook/races/race-halfling.xml",
  human:
    "https://raw.githubusercontent.com/aurorabuilder/elements/master/core/players-handbook/races/race-human.xml",
} as const;

export const BUILT_IN_SRD_RACE_ELEMENTS: readonly BuiltInElement[] = [
  {
    id: "ID_SRD_RACE_DWARF",
    type: "Race",
    name: "Dwarf",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description:
      "A durable, tradition-minded people with darkvision, poison resilience, and a dwarven subrace choice.",
    setters: [],
    rules: [
      { kind: "stat", name: "constitution", value: "2" },
      { kind: "stat", name: "innate speed", value: "25", bonus: "base" },
      { kind: "grant", type: "Size", id: "ID_SIZE_MEDIUM" },
      { kind: "grant", type: "Vision", id: "ID_VISION_DARKVISION" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_COMMON" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_DWARVISH" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_DWARVEN_RESILIENCE",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_DWARVEN_COMBAT_TRAINING",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_DWARVEN_TOOL_PROFICIENCY",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_STONECUNNING",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_DWARVEN_SUBRACE",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_DWARVEN_RESILIENCE",
    type: "Racial Trait",
    name: "Dwarven Resilience",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description:
      "You have advantage on saving throws against poison and resistance to poison damage.",
    setters: [],
    rules: [
      {
        kind: "grant",
        type: "Condition",
        id: "ID_INTERNAL_CONDITION_DAMAGE_RESISTANCE_POISON",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_DWARVEN_COMBAT_TRAINING",
    type: "Racial Trait",
    name: "Dwarven Combat Training",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description:
      "You gain proficiency with the battleaxe, handaxe, light hammer, and warhammer.",
    setters: [],
    rules: [
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_BATTLEAXE",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_HANDAXE",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_LIGHT_HAMMER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_WARHAMMER",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_DWARVEN_TOOL_PROFICIENCY",
    type: "Racial Trait",
    name: "Tool Proficiency",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description:
      "Choose one artisan tool proficiency from smith's tools, brewer's supplies, or mason's tools.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Proficiency",
        name: "Dwarven Tool Proficiency",
        supports:
          "ID_PROFICIENCY_TOOL_PROFICIENCY_SMITHS_TOOLS|ID_PROFICIENCY_TOOL_PROFICIENCY_BREWERS_SUPPLIES|ID_PROFICIENCY_TOOL_PROFICIENCY_MASONS_TOOLS",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_STONECUNNING",
    type: "Racial Trait",
    name: "Stonecunning",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description:
      "History checks related to stonework are treated as though you were proficient and add double proficiency.",
    setters: [],
    rules: [
      { kind: "stat", name: "stonecunning:check", value: "intelligence:modifier" },
      { kind: "stat", name: "stonecunning:check", value: "history:misc" },
      { kind: "stat", name: "stonecunning:check", value: "proficiency" },
      { kind: "stat", name: "stonecunning:check", value: "proficiency" },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_DWARVEN_SUBRACE",
    type: "Racial Trait",
    name: "Dwarven Subrace",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description: "Choose either Hill Dwarf or Mountain Dwarf.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Sub Race",
        name: "Dwarven Subrace",
        supports: "Dwarf",
      },
    ],
  },
  {
    id: "ID_SUB_RACE_HILL_DWARF",
    type: "Sub Race",
    name: "Hill Dwarf",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: ["Dwarf"],
    description:
      "Hill dwarves add Wisdom and the durability-focused Dwarven Toughness trait.",
    setters: [],
    rules: [
      { kind: "stat", name: "wisdom", value: "1" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_DWARVEN_TOUGHNESS",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_DWARVEN_TOUGHNESS",
    type: "Racial Trait",
    name: "Dwarven Toughness",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description:
      "Your hit point maximum increases by 1, and it increases by 1 again whenever you gain a level.",
    setters: [],
    rules: [{ kind: "stat", name: "hp", value: "level" }],
  },
  {
    id: "ID_SUB_RACE_MOUNTAIN_DWARF",
    type: "Sub Race",
    name: "Mountain Dwarf",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: ["Dwarf"],
    description:
      "Mountain dwarves add Strength and gain light and medium armor training.",
    setters: [],
    rules: [
      { kind: "stat", name: "strength", value: "2" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_DWARVEN_ARMOR_TRAINING",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_DWARVEN_ARMOR_TRAINING",
    type: "Racial Trait",
    name: "Dwarven Armor Training",
    source: SOURCE,
    source_url: SOURCE_URLS.dwarf,
    supports: [],
    description: "You gain proficiency with light and medium armor.",
    setters: [],
    rules: [
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_LIGHT_ARMOR",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_MEDIUM_ARMOR",
      },
    ],
  },
  {
    id: "ID_RACE_ELF",
    type: "Race",
    name: "Elf",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description:
      "A graceful people with darkvision, keen senses, fey ancestry, trance, and an elven subrace choice.",
    setters: [],
    rules: [
      { kind: "stat", name: "dexterity", value: "2" },
      { kind: "stat", name: "innate speed", value: "30", bonus: "base" },
      { kind: "grant", type: "Size", id: "ID_SIZE_MEDIUM" },
      { kind: "grant", type: "Vision", id: "ID_VISION_DARKVISION" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_COMMON" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_ELVISH" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_KEEN_SENSES",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_FEY_ANCESTRY",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_TRANCE",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_ELVEN_SUBRACE",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_KEEN_SENSES",
    type: "Racial Trait",
    name: "Keen Senses",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description: "You gain proficiency in Perception.",
    setters: [],
    rules: [
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_SKILL_PERCEPTION",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_FEY_ANCESTRY",
    type: "Racial Trait",
    name: "Fey Ancestry",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description:
      "You have advantage on saves against being charmed, and magic can't put you to sleep.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_RACIAL_TRAIT_TRANCE",
    type: "Racial Trait",
    name: "Trance",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description: "You meditate for 4 hours instead of sleeping to gain a long rest's benefit.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_RACIAL_TRAIT_ELVEN_SUBRACE",
    type: "Racial Trait",
    name: "Elven Subrace",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description: "Choose either High Elf or Wood Elf.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Sub Race",
        name: "Elven Subrace",
        supports: "Elf",
      },
    ],
  },
  {
    id: "ID_SUB_RACE_HIGH_ELF",
    type: "Sub Race",
    name: "High Elf",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: ["Elf"],
    description:
      "High elves add Intelligence, weapon training, a wizard cantrip choice, and one extra language.",
    setters: [],
    rules: [
      { kind: "stat", name: "intelligence", value: "1" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_ELF_WEAPON_TRAINING",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_CANTRIP",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_EXTRA_LANGUAGE",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_ELF_WEAPON_TRAINING",
    type: "Racial Trait",
    name: "Elf Weapon Training",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description:
      "You gain proficiency with the longsword, shortsword, shortbow, and longbow.",
    setters: [],
    rules: [
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_LONGSWORD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_SHORTSWORD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_SHORTBOW",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_LONGBOW",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_CANTRIP",
    type: "Racial Trait",
    name: "Cantrip",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description:
      "You know one wizard cantrip of your choice, and Intelligence is your spellcasting ability for it.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Spell",
        name: "Wizard Cantrip (High Elf)",
        supports: "Wizard&&0",
      },
    ],
    spellcasting: {
      ability: "intelligence",
      name: "High Elf Cantrip",
    },
  },
  {
    id: "ID_RACIAL_TRAIT_EXTRA_LANGUAGE",
    type: "Racial Trait",
    name: "Extra Language",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description: "You can speak, read, and write one extra language of your choice.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Language",
        name: "Language (Elf)",
        supports: "Standard||Exotic",
      },
    ],
  },
  {
    id: "ID_SUB_RACE_WOOD_ELF",
    type: "Sub Race",
    name: "Wood Elf",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: ["Elf"],
    description:
      "Wood elves add Wisdom, elven weapon training, extra speed, and a natural-world stealth benefit.",
    setters: [],
    rules: [
      { kind: "stat", name: "wisdom", value: "1" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_ELF_WEAPON_TRAINING",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_FLEET_OF_FOOT",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_MASK_OF_THE_WILD",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_FLEET_OF_FOOT",
    type: "Racial Trait",
    name: "Fleet of Foot",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description: "Your base walking speed increases to 35 feet.",
    setters: [],
    rules: [{ kind: "stat", name: "innate speed", value: "35", bonus: "base" }],
  },
  {
    id: "ID_RACIAL_TRAIT_MASK_OF_THE_WILD",
    type: "Racial Trait",
    name: "Mask of the Wild",
    source: SOURCE,
    source_url: SOURCE_URLS.elf,
    supports: [],
    description:
      "You can attempt to hide while only lightly obscured by natural phenomena.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_RACE_HALFLING",
    type: "Race",
    name: "Halfling",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description:
      "A nimble, lucky people with Brave, Halfling Nimbleness, and a halfling subrace choice.",
    setters: [],
    rules: [
      { kind: "stat", name: "dexterity", value: "2" },
      { kind: "stat", name: "innate speed", value: "25", bonus: "base" },
      { kind: "grant", type: "Size", id: "ID_SIZE_SMALL" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_COMMON" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_HALFLING" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_LUCKY",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_BRAVE",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_HALFLING_NIMBLENESS",
      },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_HALFLING_SUBRACE",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_LUCKY",
    type: "Racial Trait",
    name: "Lucky",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description: "When you roll a 1 on a d20 test, you can reroll the die.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_RACIAL_TRAIT_BRAVE",
    type: "Racial Trait",
    name: "Brave",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description: "You have advantage on saving throws against being frightened.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_RACIAL_TRAIT_HALFLING_NIMBLENESS",
    type: "Racial Trait",
    name: "Halfling Nimbleness",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description: "You can move through the space of creatures larger than you.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_RACIAL_TRAIT_HALFLING_SUBRACE",
    type: "Racial Trait",
    name: "Halfling Subrace",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description: "Choose either Lightfoot Halfling or Stout Halfling.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Sub Race",
        name: "Halfling Subrace",
        supports: "Halfling",
      },
    ],
  },
  {
    id: "ID_SUB_RACE_LIGHTFOOT_HALFLING",
    type: "Sub Race",
    name: "Lightfoot Halfling",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: ["Halfling"],
    description:
      "Lightfoot halflings add Charisma and can hide behind creatures larger than they are.",
    setters: [],
    rules: [
      { kind: "stat", name: "charisma", value: "1" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_NATURALLY_STEALTHY",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_NATURALLY_STEALTHY",
    type: "Racial Trait",
    name: "Naturally Stealthy",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description:
      "You can attempt to hide behind a creature at least one size larger than you.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_SUB_RACE_STOUT_HALFLING",
    type: "Sub Race",
    name: "Stout Halfling",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: ["Halfling"],
    description:
      "Stout halflings add Constitution and gain poison resilience similar to dwarves.",
    setters: [],
    rules: [
      { kind: "stat", name: "constitution", value: "1" },
      {
        kind: "grant",
        type: "Racial Trait",
        id: "ID_RACIAL_TRAIT_STOUT_RESILIENCE",
      },
    ],
  },
  {
    id: "ID_RACIAL_TRAIT_STOUT_RESILIENCE",
    type: "Racial Trait",
    name: "Stout Resilience",
    source: SOURCE,
    source_url: SOURCE_URLS.halfling,
    supports: [],
    description:
      "You have advantage on saving throws against poison and resistance to poison damage.",
    setters: [],
    rules: [
      {
        kind: "grant",
        type: "Condition",
        id: "ID_INTERNAL_CONDITION_DAMAGE_RESISTANCE_POISON",
      },
    ],
  },
  {
    id: "ID_RACE_HUMAN",
    type: "Race",
    name: "Human",
    source: SOURCE,
    source_url: SOURCE_URLS.human,
    supports: [],
    description:
      "A flexible people with +1 to every ability score, normal speed, Common, and one extra language choice.",
    setters: [],
    rules: [
      { kind: "stat", name: "strength", value: "1" },
      { kind: "stat", name: "dexterity", value: "1" },
      { kind: "stat", name: "constitution", value: "1" },
      { kind: "stat", name: "intelligence", value: "1" },
      { kind: "stat", name: "wisdom", value: "1" },
      { kind: "stat", name: "charisma", value: "1" },
      { kind: "grant", type: "Size", id: "ID_SIZE_MEDIUM" },
      { kind: "stat", name: "innate speed", value: "30", bonus: "base" },
      { kind: "grant", type: "Language", id: "ID_LANGUAGE_COMMON" },
      {
        kind: "select",
        type: "Language",
        name: "Language (Human)",
        supports: "Standard||Exotic",
      },
    ],
  },
] as const;
