import type { BuiltInElement } from "@/lib/builtins/types";

const SOURCE = "System Reference Document 5.1";

const SOURCE_URLS = {
  fighter:
    "https://raw.githubusercontent.com/aurorabuilder/elements/master/core/players-handbook/classes/class-fighter.xml",
  wizard:
    "https://raw.githubusercontent.com/aurorabuilder/elements/master/core/players-handbook/classes/class-wizard.xml",
} as const;

export const BUILT_IN_SRD_CLASS_ELEMENTS: readonly BuiltInElement[] = [
  {
    id: "ID_WOTC_PHB_CLASS_FIGHTER",
    type: "Class",
    name: "Fighter",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "A master of martial combat, skilled with a variety of weapons and armor.",
    setters: [
      {
        name: "short",
        value: "A master of martial combat, skilled with a variety of weapons and armor.",
      },
      { name: "hd", value: "d10" },
    ],
    rules: [
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_LIGHT_ARMOR",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_MEDIUM_ARMOR",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_HEAVY_ARMOR",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_SHIELDS",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_SIMPLE_WEAPONS",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_MARTIAL_WEAPONS",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_SAVINGTHROW_STRENGTH",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_SAVINGTHROW_CONSTITUTION",
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "select",
        type: "Proficiency",
        name: "Skill Proficiency (Fighter)",
        supports: "Skill,Fighter",
        number: 2,
        requirements: "!ID_WOTC_PHB_MULTICLASS_FIGHTER",
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_FIGHTINGSTYLE",
        level: 1,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_SECONDWIND",
        level: 1,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_ACTIONSURGE",
        level: 2,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_MARTIALARCHETYPE",
        level: 3,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_ABILITYSCOREIMPROVEMENT_FIGHTER",
        level: 4,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_EXTRAATTACK",
        level: 5,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_INDOMITABLE",
        level: 9,
      },
    ],
    multiclass: {
      requirements: "([str:13]||[dex:13])",
      requirementsDescription: "Strength 13 or Dexterity 13",
      setters: [
        {
          name: "multiclass proficiencies",
          value: "Light armor, medium armor, shields, simple weapons, martial weapons",
        },
      ],
      rules: [
        { kind: "grant", type: "Grants", id: "ID_INTERNAL_GRANT_MULTICLASS" },
        {
          kind: "grant",
          type: "Proficiency",
          id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_LIGHT_ARMOR",
        },
        {
          kind: "grant",
          type: "Proficiency",
          id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_MEDIUM_ARMOR",
        },
        {
          kind: "grant",
          type: "Proficiency",
          id: "ID_PROFICIENCY_ARMOR_PROFICIENCY_SHIELDS",
        },
        {
          kind: "grant",
          type: "Proficiency",
          id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_SIMPLE_WEAPONS",
        },
        {
          kind: "grant",
          type: "Proficiency",
          id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_MARTIAL_WEAPONS",
        },
      ],
    },
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_FIGHTINGSTYLE",
    type: "Class Feature",
    name: "Fighting Style",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Choose a martial specialty such as Archery, Defense, or Great Weapon Fighting.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Class Feature",
        name: "Fighting Style",
        supports: "Fighting Style, Fighter",
        level: 1,
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_SECONDWIND",
    type: "Class Feature",
    name: "Second Wind",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Use a bonus action to regain hit points equal to 1d10 + your fighter level once per short or long rest.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_ACTIONSURGE",
    type: "Class Feature",
    name: "Action Surge",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Push beyond your normal limits to take one additional action on your turn.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_MARTIALARCHETYPE",
    type: "Class Feature",
    name: "Martial Archetype",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Choose a martial archetype at 3rd level, then gain additional archetype features as you level.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Archetype",
        name: "Martial Archetype",
        supports: "Martial Archetype",
        level: 3,
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_ABILITYSCOREIMPROVEMENT_FIGHTER",
    type: "Class Feature",
    name: "Ability Score Improvement",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Improve your abilities at 4th, 6th, 8th, 12th, 14th, 16th, and 19th fighter level.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 4)",
        supports: "Improvement Option,Fighter,4",
        level: 4,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 6)",
        supports: "Improvement Option,Fighter,6",
        level: 6,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 8)",
        supports: "Improvement Option,Fighter,8",
        level: 8,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 12)",
        supports: "Improvement Option,Fighter,12",
        level: 12,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 14)",
        supports: "Improvement Option,Fighter,14",
        level: 14,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 16)",
        supports: "Improvement Option,Fighter,16",
        level: 16,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Fighter 19)",
        supports: "Improvement Option,Fighter,19",
        level: 19,
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_EXTRAATTACK",
    type: "Class Feature",
    name: "Extra Attack",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Attack more than once when you take the Attack action, eventually reaching four attacks at 20th level.",
    setters: [],
    rules: [
      {
        kind: "stat",
        name: "extra attack:count",
        value: "2",
        level: 5,
        bonus: "extra attack",
      },
      {
        kind: "stat",
        name: "extra attack:count",
        value: "3",
        level: 11,
        bonus: "extra attack",
      },
      {
        kind: "stat",
        name: "extra attack:count",
        value: "4",
        level: 20,
        bonus: "extra attack",
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_INDOMITABLE",
    type: "Class Feature",
    name: "Indomitable",
    source: SOURCE,
    source_url: SOURCE_URLS.fighter,
    supports: [],
    description:
      "Reroll a failed saving throw, with additional uses gained at higher levels.",
    setters: [],
    rules: [
      { kind: "stat", name: "indomitable:usage", value: "1", level: 9 },
      { kind: "stat", name: "indomitable:usage", value: "1", level: 13 },
      { kind: "stat", name: "indomitable:usage", value: "1", level: 17 },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_WIZARD",
    type: "Class",
    name: "Wizard",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "A scholarly magic-user capable of manipulating the structures of reality.",
    setters: [
      {
        name: "short",
        value:
          "A scholarly magic-user capable of manipulating the structures of reality.",
      },
      { name: "hd", value: "d6" },
    ],
    rules: [
      {
        kind: "grant",
        type: "Grants",
        id: "ID_INTERNAL_GRANT_MULTICLASS_SPELLCASTING_SLOTS_FULL",
        requirements: "ID_INTERNAL_GRANT_MULTICLASS",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_DAGGER",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_DART",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_SLING",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_QUARTERSTAFF",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_WEAPON_PROFICIENCY_CROSSBOW_LIGHT",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_SAVINGTHROW_INTELLIGENCE",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_PROFICIENCY_SAVINGTHROW_WISDOM",
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "select",
        type: "Proficiency",
        name: "Skill Proficiency (Wizard)",
        supports: "Skill,Wizard",
        number: 2,
        requirements: "!ID_WOTC_PHB_MULTICLASS_WIZARD",
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_SPELLCASTING_WIZARD",
        level: 1,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_ARCANE_RECOVERY",
        level: 1,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_ARCANE_TRADITION",
        level: 2,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_ABILITYSCOREIMPROVEMENT_WIZARD",
        level: 4,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_SPELL_MASTERY",
        level: 18,
      },
      {
        kind: "grant",
        type: "Class Feature",
        id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_SIGNATURE_SPELLS",
        level: 20,
      },
    ],
    multiclass: {
      requirements: "[int:13]",
      requirementsDescription: "Intelligence 13",
      setters: [{ name: "multiclass proficiencies", value: "—" }],
      rules: [{ kind: "grant", type: "Grants", id: "ID_INTERNAL_GRANT_MULTICLASS" }],
    },
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_SPELLCASTING_WIZARD",
    type: "Class Feature",
    name: "Spellcasting",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "Prepare wizard spells from a spellbook, cast rituals, and scale spell slots through full-caster progression.",
    setters: [],
    spellcasting: {
      name: "Wizard",
      ability: "Intelligence",
    },
    rules: [
      { kind: "grant", type: "Grants", id: "ID_INTERNAL_RITUAL_CASTING" },
      {
        kind: "grant",
        type: "Proficiency",
        id: "ID_INTERNAL_PROFICIENCY_SPELLFOCUS_GROUP_ARCANE_FOCUS",
      },
      { kind: "stat", name: "wizard:spellcasting:slots:1", value: "2", level: 1 },
      { kind: "stat", name: "wizard:spellcasting:slots:1", value: "1", level: 2 },
      { kind: "stat", name: "wizard:spellcasting:slots:1", value: "1", level: 3 },
      { kind: "stat", name: "wizard:spellcasting:slots:2", value: "2", level: 3 },
      { kind: "stat", name: "wizard:spellcasting:slots:2", value: "1", level: 4 },
      { kind: "stat", name: "wizard:spellcasting:slots:3", value: "2", level: 5 },
      { kind: "stat", name: "wizard:spellcasting:slots:3", value: "1", level: 6 },
      { kind: "stat", name: "wizard:spellcasting:slots:4", value: "1", level: 7 },
      { kind: "stat", name: "wizard:spellcasting:slots:4", value: "1", level: 8 },
      { kind: "stat", name: "wizard:spellcasting:slots:4", value: "1", level: 9 },
      { kind: "stat", name: "wizard:spellcasting:slots:5", value: "1", level: 9 },
      { kind: "stat", name: "wizard:spellcasting:slots:5", value: "1", level: 10 },
      { kind: "stat", name: "wizard:spellcasting:slots:5", value: "1", level: 18 },
      { kind: "stat", name: "wizard:spellcasting:slots:6", value: "1", level: 11 },
      { kind: "stat", name: "wizard:spellcasting:slots:6", value: "1", level: 19 },
      { kind: "stat", name: "wizard:spellcasting:slots:7", value: "1", level: 13 },
      { kind: "stat", name: "wizard:spellcasting:slots:7", value: "1", level: 20 },
      { kind: "stat", name: "wizard:spellcasting:slots:8", value: "1", level: 15 },
      { kind: "stat", name: "wizard:spellcasting:slots:9", value: "1", level: 17 },
      {
        kind: "stat",
        name: "wizard:spellcasting:prepare",
        value: "intelligence:modifier",
      },
      { kind: "stat", name: "wizard:spellcasting:prepare", value: "level:wizard" },
      {
        kind: "select",
        type: "Spell",
        name: "Cantrip (Wizard)",
        supports: "$(spellcasting:list), 0",
        level: 1,
        number: 3,
      },
      {
        kind: "select",
        type: "Spell",
        name: "Cantrip (Wizard)",
        supports: "$(spellcasting:list), 0",
        level: 4,
        number: 1,
      },
      {
        kind: "select",
        type: "Spell",
        name: "Cantrip (Wizard)",
        supports: "$(spellcasting:list), 0",
        level: 10,
        number: 1,
      },
      {
        kind: "select",
        type: "Spell",
        name: "Spellbook (Wizard)",
        supports: "$(spellcasting:list), 1",
        level: 1,
        number: 6,
      },
      {
        kind: "select",
        type: "Spell",
        name: "Spellbook (Wizard)",
        supports: "$(spellcasting:list), $(spellcasting:slots)",
        level: 2,
        number: 2,
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_ARCANE_RECOVERY",
    type: "Class Feature",
    name: "Arcane Recovery",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "Recover expended spell slots during a short rest up to a combined level equal to half your wizard level, rounded up.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_ARCANE_TRADITION",
    type: "Class Feature",
    name: "Arcane Tradition",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "Choose an arcane tradition at 2nd level to shape your magical studies.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Archetype",
        name: "Arcane Tradition",
        supports: "Arcane Tradition",
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_ABILITYSCOREIMPROVEMENT_WIZARD",
    type: "Class Feature",
    name: "Ability Score Improvement",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "Improve your abilities at 4th, 8th, 12th, 16th, and 19th wizard level.",
    setters: [],
    rules: [
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Wizard 4)",
        supports: "Improvement Option,Wizard,4",
        level: 4,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Wizard 8)",
        supports: "Improvement Option,Wizard,8",
        level: 8,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Wizard 12)",
        supports: "Improvement Option,Wizard,12",
        level: 12,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Wizard 16)",
        supports: "Improvement Option,Wizard,16",
        level: 16,
      },
      {
        kind: "select",
        type: "Class Feature",
        name: "Improvement Option (Wizard 19)",
        supports: "Improvement Option,Wizard,19",
        level: 19,
      },
    ],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_SPELL_MASTERY",
    type: "Class Feature",
    name: "Spell Mastery",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "Master a 1st-level and 2nd-level wizard spell so you can cast them without expending spell slots.",
    setters: [],
    rules: [],
  },
  {
    id: "ID_WOTC_PHB_CLASS_FEATURE_WIZARD_SIGNATURE_SPELLS",
    type: "Class Feature",
    name: "Signature Spells",
    source: SOURCE,
    source_url: SOURCE_URLS.wizard,
    supports: [],
    description:
      "Choose two 3rd-level wizard spells in your spellbook as signature spells at 20th level.",
    setters: [],
    rules: [],
  },
] as const;
